// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: internal/plugins/proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Plugin_Init_FullMethodName            = "/census.plugin.Plugin/Init"
	Plugin_Start_FullMethodName           = "/census.plugin.Plugin/Start"
	Plugin_Stop_FullMethodName            = "/census.plugin.Plugin/Stop"
	Plugin_Healthcheck_FullMethodName     = "/census.plugin.Plugin/Healthcheck"
	Plugin_GetInfo_FullMethodName         = "/census.plugin.Plugin/GetInfo"
	Plugin_GetTab_FullMethodName          = "/census.plugin.Plugin/GetTab"
	Plugin_GetBadges_FullMethodName       = "/census.plugin.Plugin/GetBadges"
	Plugin_HandleRoute_FullMethodName     = "/census.plugin.Plugin/HandleRoute"
	Plugin_EnrichContainer_FullMethodName = "/census.plugin.Plugin/EnrichContainer"
	Plugin_HandleEvent_FullMethodName     = "/census.plugin.Plugin/HandleEvent"
	Plugin_GetSettings_FullMethodName     = "/census.plugin.Plugin/GetSettings"
	Plugin_UpdateSettings_FullMethodName  = "/census.plugin.Plugin/UpdateSettings"
)

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Plugin service - implemented by external plugin processes
type PluginClient interface {
	// Lifecycle methods
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error)
	// Capability methods
	GetInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	GetTab(ctx context.Context, in *TabRequest, opts ...grpc.CallOption) (*TabResponse, error)
	GetBadges(ctx context.Context, in *BadgesRequest, opts ...grpc.CallOption) (*BadgesResponse, error)
	HandleRoute(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
	EnrichContainer(ctx context.Context, in *EnrichRequest, opts ...grpc.CallOption) (*EnrichResponse, error)
	HandleEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	GetSettings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*SettingsResponse, error)
	UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*UpdateSettingsResponse, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, Plugin_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, Plugin_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, Plugin_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Healthcheck(ctx context.Context, in *HealthcheckRequest, opts ...grpc.CallOption) (*HealthcheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthcheckResponse)
	err := c.cc.Invoke(ctx, Plugin_Healthcheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) GetInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, Plugin_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) GetTab(ctx context.Context, in *TabRequest, opts ...grpc.CallOption) (*TabResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TabResponse)
	err := c.cc.Invoke(ctx, Plugin_GetTab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) GetBadges(ctx context.Context, in *BadgesRequest, opts ...grpc.CallOption) (*BadgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BadgesResponse)
	err := c.cc.Invoke(ctx, Plugin_GetBadges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) HandleRoute(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, Plugin_HandleRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) EnrichContainer(ctx context.Context, in *EnrichRequest, opts ...grpc.CallOption) (*EnrichResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichResponse)
	err := c.cc.Invoke(ctx, Plugin_EnrichContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) HandleEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, Plugin_HandleEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) GetSettings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*SettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingsResponse)
	err := c.cc.Invoke(ctx, Plugin_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*UpdateSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSettingsResponse)
	err := c.cc.Invoke(ctx, Plugin_UpdateSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
// All implementations must embed UnimplementedPluginServer
// for forward compatibility.
//
// Plugin service - implemented by external plugin processes
type PluginServer interface {
	// Lifecycle methods
	Init(context.Context, *InitRequest) (*InitResponse, error)
	Start(context.Context, *StartRequest) (*StartResponse, error)
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	Healthcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error)
	// Capability methods
	GetInfo(context.Context, *InfoRequest) (*InfoResponse, error)
	GetTab(context.Context, *TabRequest) (*TabResponse, error)
	GetBadges(context.Context, *BadgesRequest) (*BadgesResponse, error)
	HandleRoute(context.Context, *RouteRequest) (*RouteResponse, error)
	EnrichContainer(context.Context, *EnrichRequest) (*EnrichResponse, error)
	HandleEvent(context.Context, *EventRequest) (*EventResponse, error)
	GetSettings(context.Context, *SettingsRequest) (*SettingsResponse, error)
	UpdateSettings(context.Context, *UpdateSettingsRequest) (*UpdateSettingsResponse, error)
	mustEmbedUnimplementedPluginServer()
}

// UnimplementedPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServer struct{}

func (UnimplementedPluginServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedPluginServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedPluginServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedPluginServer) Healthcheck(context.Context, *HealthcheckRequest) (*HealthcheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Healthcheck not implemented")
}
func (UnimplementedPluginServer) GetInfo(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedPluginServer) GetTab(context.Context, *TabRequest) (*TabResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTab not implemented")
}
func (UnimplementedPluginServer) GetBadges(context.Context, *BadgesRequest) (*BadgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBadges not implemented")
}
func (UnimplementedPluginServer) HandleRoute(context.Context, *RouteRequest) (*RouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleRoute not implemented")
}
func (UnimplementedPluginServer) EnrichContainer(context.Context, *EnrichRequest) (*EnrichResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichContainer not implemented")
}
func (UnimplementedPluginServer) HandleEvent(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleEvent not implemented")
}
func (UnimplementedPluginServer) GetSettings(context.Context, *SettingsRequest) (*SettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedPluginServer) UpdateSettings(context.Context, *UpdateSettingsRequest) (*UpdateSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSettings not implemented")
}
func (UnimplementedPluginServer) mustEmbedUnimplementedPluginServer() {}
func (UnimplementedPluginServer) testEmbeddedByValue()                {}

// UnsafePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServer will
// result in compilation errors.
type UnsafePluginServer interface {
	mustEmbedUnimplementedPluginServer()
}

func RegisterPluginServer(s grpc.ServiceRegistrar, srv PluginServer) {
	// If the following call panics, it indicates UnimplementedPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Plugin_ServiceDesc, srv)
}

func _Plugin_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Healthcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Healthcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_Healthcheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Healthcheck(ctx, req.(*HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).GetInfo(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_GetTab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).GetTab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_GetTab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).GetTab(ctx, req.(*TabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_GetBadges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BadgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).GetBadges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_GetBadges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).GetBadges(ctx, req.(*BadgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_HandleRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).HandleRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_HandleRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).HandleRoute(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_EnrichContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).EnrichContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_EnrichContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).EnrichContainer(ctx, req.(*EnrichRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_HandleEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).HandleEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_HandleEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).HandleEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).GetSettings(ctx, req.(*SettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_UpdateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).UpdateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_UpdateSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).UpdateSettings(ctx, req.(*UpdateSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugin_ServiceDesc is the grpc.ServiceDesc for Plugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "census.plugin.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Plugin_Init_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Plugin_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Plugin_Stop_Handler,
		},
		{
			MethodName: "Healthcheck",
			Handler:    _Plugin_Healthcheck_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _Plugin_GetInfo_Handler,
		},
		{
			MethodName: "GetTab",
			Handler:    _Plugin_GetTab_Handler,
		},
		{
			MethodName: "GetBadges",
			Handler:    _Plugin_GetBadges_Handler,
		},
		{
			MethodName: "HandleRoute",
			Handler:    _Plugin_HandleRoute_Handler,
		},
		{
			MethodName: "EnrichContainer",
			Handler:    _Plugin_EnrichContainer_Handler,
		},
		{
			MethodName: "HandleEvent",
			Handler:    _Plugin_HandleEvent_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _Plugin_GetSettings_Handler,
		},
		{
			MethodName: "UpdateSettings",
			Handler:    _Plugin_UpdateSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/plugins/proto/plugin.proto",
}

const (
	CensusAPI_GetContainers_FullMethodName    = "/census.plugin.CensusAPI/GetContainers"
	CensusAPI_GetContainer_FullMethodName     = "/census.plugin.CensusAPI/GetContainer"
	CensusAPI_GetHosts_FullMethodName         = "/census.plugin.CensusAPI/GetHosts"
	CensusAPI_GetHost_FullMethodName          = "/census.plugin.CensusAPI/GetHost"
	CensusAPI_GetPluginData_FullMethodName    = "/census.plugin.CensusAPI/GetPluginData"
	CensusAPI_SetPluginData_FullMethodName    = "/census.plugin.CensusAPI/SetPluginData"
	CensusAPI_DeletePluginData_FullMethodName = "/census.plugin.CensusAPI/DeletePluginData"
	CensusAPI_Log_FullMethodName              = "/census.plugin.CensusAPI/Log"
	CensusAPI_SendEvent_FullMethodName        = "/census.plugin.CensusAPI/SendEvent"
)

// CensusAPIClient is the client API for CensusAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Census API service - implemented by main server (callback API for plugins)
type CensusAPIClient interface {
	GetContainers(ctx context.Context, in *GetContainersRequest, opts ...grpc.CallOption) (*GetContainersResponse, error)
	GetContainer(ctx context.Context, in *GetContainerRequest, opts ...grpc.CallOption) (*GetContainerResponse, error)
	GetHosts(ctx context.Context, in *GetHostsRequest, opts ...grpc.CallOption) (*GetHostsResponse, error)
	GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*GetHostResponse, error)
	GetPluginData(ctx context.Context, in *GetPluginDataRequest, opts ...grpc.CallOption) (*GetPluginDataResponse, error)
	SetPluginData(ctx context.Context, in *SetPluginDataRequest, opts ...grpc.CallOption) (*SetPluginDataResponse, error)
	DeletePluginData(ctx context.Context, in *DeletePluginDataRequest, opts ...grpc.CallOption) (*DeletePluginDataResponse, error)
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	SendEvent(ctx context.Context, in *SendEventRequest, opts ...grpc.CallOption) (*SendEventResponse, error)
}

type censusAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewCensusAPIClient(cc grpc.ClientConnInterface) CensusAPIClient {
	return &censusAPIClient{cc}
}

func (c *censusAPIClient) GetContainers(ctx context.Context, in *GetContainersRequest, opts ...grpc.CallOption) (*GetContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContainersResponse)
	err := c.cc.Invoke(ctx, CensusAPI_GetContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *censusAPIClient) GetContainer(ctx context.Context, in *GetContainerRequest, opts ...grpc.CallOption) (*GetContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContainerResponse)
	err := c.cc.Invoke(ctx, CensusAPI_GetContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *censusAPIClient) GetHosts(ctx context.Context, in *GetHostsRequest, opts ...grpc.CallOption) (*GetHostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostsResponse)
	err := c.cc.Invoke(ctx, CensusAPI_GetHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *censusAPIClient) GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*GetHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostResponse)
	err := c.cc.Invoke(ctx, CensusAPI_GetHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *censusAPIClient) GetPluginData(ctx context.Context, in *GetPluginDataRequest, opts ...grpc.CallOption) (*GetPluginDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPluginDataResponse)
	err := c.cc.Invoke(ctx, CensusAPI_GetPluginData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *censusAPIClient) SetPluginData(ctx context.Context, in *SetPluginDataRequest, opts ...grpc.CallOption) (*SetPluginDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPluginDataResponse)
	err := c.cc.Invoke(ctx, CensusAPI_SetPluginData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *censusAPIClient) DeletePluginData(ctx context.Context, in *DeletePluginDataRequest, opts ...grpc.CallOption) (*DeletePluginDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePluginDataResponse)
	err := c.cc.Invoke(ctx, CensusAPI_DeletePluginData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *censusAPIClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, CensusAPI_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *censusAPIClient) SendEvent(ctx context.Context, in *SendEventRequest, opts ...grpc.CallOption) (*SendEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEventResponse)
	err := c.cc.Invoke(ctx, CensusAPI_SendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CensusAPIServer is the server API for CensusAPI service.
// All implementations must embed UnimplementedCensusAPIServer
// for forward compatibility.
//
// Census API service - implemented by main server (callback API for plugins)
type CensusAPIServer interface {
	GetContainers(context.Context, *GetContainersRequest) (*GetContainersResponse, error)
	GetContainer(context.Context, *GetContainerRequest) (*GetContainerResponse, error)
	GetHosts(context.Context, *GetHostsRequest) (*GetHostsResponse, error)
	GetHost(context.Context, *GetHostRequest) (*GetHostResponse, error)
	GetPluginData(context.Context, *GetPluginDataRequest) (*GetPluginDataResponse, error)
	SetPluginData(context.Context, *SetPluginDataRequest) (*SetPluginDataResponse, error)
	DeletePluginData(context.Context, *DeletePluginDataRequest) (*DeletePluginDataResponse, error)
	Log(context.Context, *LogRequest) (*LogResponse, error)
	SendEvent(context.Context, *SendEventRequest) (*SendEventResponse, error)
	mustEmbedUnimplementedCensusAPIServer()
}

// UnimplementedCensusAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCensusAPIServer struct{}

func (UnimplementedCensusAPIServer) GetContainers(context.Context, *GetContainersRequest) (*GetContainersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContainers not implemented")
}
func (UnimplementedCensusAPIServer) GetContainer(context.Context, *GetContainerRequest) (*GetContainerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContainer not implemented")
}
func (UnimplementedCensusAPIServer) GetHosts(context.Context, *GetHostsRequest) (*GetHostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHosts not implemented")
}
func (UnimplementedCensusAPIServer) GetHost(context.Context, *GetHostRequest) (*GetHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHost not implemented")
}
func (UnimplementedCensusAPIServer) GetPluginData(context.Context, *GetPluginDataRequest) (*GetPluginDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginData not implemented")
}
func (UnimplementedCensusAPIServer) SetPluginData(context.Context, *SetPluginDataRequest) (*SetPluginDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPluginData not implemented")
}
func (UnimplementedCensusAPIServer) DeletePluginData(context.Context, *DeletePluginDataRequest) (*DeletePluginDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePluginData not implemented")
}
func (UnimplementedCensusAPIServer) Log(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedCensusAPIServer) SendEvent(context.Context, *SendEventRequest) (*SendEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedCensusAPIServer) mustEmbedUnimplementedCensusAPIServer() {}
func (UnimplementedCensusAPIServer) testEmbeddedByValue()                   {}

// UnsafeCensusAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CensusAPIServer will
// result in compilation errors.
type UnsafeCensusAPIServer interface {
	mustEmbedUnimplementedCensusAPIServer()
}

func RegisterCensusAPIServer(s grpc.ServiceRegistrar, srv CensusAPIServer) {
	// If the following call panics, it indicates UnimplementedCensusAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CensusAPI_ServiceDesc, srv)
}

func _CensusAPI_GetContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CensusAPIServer).GetContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CensusAPI_GetContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CensusAPIServer).GetContainers(ctx, req.(*GetContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CensusAPI_GetContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CensusAPIServer).GetContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CensusAPI_GetContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CensusAPIServer).GetContainer(ctx, req.(*GetContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CensusAPI_GetHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CensusAPIServer).GetHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CensusAPI_GetHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CensusAPIServer).GetHosts(ctx, req.(*GetHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CensusAPI_GetHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CensusAPIServer).GetHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CensusAPI_GetHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CensusAPIServer).GetHost(ctx, req.(*GetHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CensusAPI_GetPluginData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CensusAPIServer).GetPluginData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CensusAPI_GetPluginData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CensusAPIServer).GetPluginData(ctx, req.(*GetPluginDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CensusAPI_SetPluginData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPluginDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CensusAPIServer).SetPluginData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CensusAPI_SetPluginData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CensusAPIServer).SetPluginData(ctx, req.(*SetPluginDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CensusAPI_DeletePluginData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePluginDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CensusAPIServer).DeletePluginData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CensusAPI_DeletePluginData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CensusAPIServer).DeletePluginData(ctx, req.(*DeletePluginDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CensusAPI_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CensusAPIServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CensusAPI_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CensusAPIServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CensusAPI_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CensusAPIServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CensusAPI_SendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CensusAPIServer).SendEvent(ctx, req.(*SendEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CensusAPI_ServiceDesc is the grpc.ServiceDesc for CensusAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CensusAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "census.plugin.CensusAPI",
	HandlerType: (*CensusAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContainers",
			Handler:    _CensusAPI_GetContainers_Handler,
		},
		{
			MethodName: "GetContainer",
			Handler:    _CensusAPI_GetContainer_Handler,
		},
		{
			MethodName: "GetHosts",
			Handler:    _CensusAPI_GetHosts_Handler,
		},
		{
			MethodName: "GetHost",
			Handler:    _CensusAPI_GetHost_Handler,
		},
		{
			MethodName: "GetPluginData",
			Handler:    _CensusAPI_GetPluginData_Handler,
		},
		{
			MethodName: "SetPluginData",
			Handler:    _CensusAPI_SetPluginData_Handler,
		},
		{
			MethodName: "DeletePluginData",
			Handler:    _CensusAPI_DeletePluginData_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _CensusAPI_Log_Handler,
		},
		{
			MethodName: "SendEvent",
			Handler:    _CensusAPI_SendEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/plugins/proto/plugin.proto",
}
